new branch with git.
Nitroglicerine/JavaScript-exercises pull request #1
Opened 2023-11-08 20:17 UTC by Nitroglicerine

We testitng pull Request with gitHub.

2023-11-08 20:20 UTC, Nitroglicerine commented
I was  changed  class with module "Vehicle.js"

2023-11-09 16:56 UTC, bringmetheaugust reviewed
не ідеально. перероби

2023-11-09 16:56 UTC, bringmetheaugust commented on src/transport/Vehicle.js
> +      this.productYear = productYear
нахуй там кома? кожна строка - це окрема операція

2023-11-09 17:07 UTC, bringmetheaugust requested changes
і це перероби

2023-11-09 17:07 UTC, bringmetheaugust commented on src/oop.js
>  import  Jet  from "./transport/Jet.js"
і зараз всі користуються одинарними кавичками, тобто **'** замість **"**

2023-11-09 21:59 UTC, merged