Create new modules, and sorting tasks
Nitroglicerine/JavaScript-exercises pull request #5
Opened 2023-11-30 04:03 UTC by Nitroglicerine

Please see, and send mee feedback

2023-11-30 20:58 UTC, bringmetheaugust requested changes
перероби

2023-11-30 20:58 UTC, bringmetheaugust commented on src/alphabetNumberTask.js
> +export{foundLettersNum}
некрасівий імпорт.
роби так:
```
export function olegLoh() {
   // your code
}
```

2023-12-01 03:09 UTC, Nitroglicerine commented on src/alphabetNumberTask.js
> +export{foundLettersNum}
Done

2023-12-02 23:53 UTC, bringmetheaugust requested changes

2023-12-06 13:23 UTC, merged