New tasks is done.
Nitroglicerine/JavaScript-exercises pull request #6
Opened 2023-12-11 15:56 UTC by Nitroglicerine

I get done two new tasks. 
First task ist big graphic with console . 
I used two cykles. and `If - else` -statement. 
Second task  subtract one numbers for all letters in string. 
I used unicode format methods, and cykle.

2023-12-11 23:18 UTC, bringmetheaugust requested changes
перероби

2023-12-11 23:18 UTC, bringmetheaugust commented on src/setOneDownTask.js
> +    if (typeof str === "string") {
де отступ?

2023-12-11 23:18 UTC, bringmetheaugust commented on src/setOneDownTask.js
> +
зачем тут отступ?

2023-12-11 23:18 UTC, bringmetheaugust commented on src/setOneDownTask.js
> +        }
тут можна тернарник

2023-12-15 01:40 UTC, bringmetheaugust requested changes
переробити

2023-12-15 01:40 UTC, bringmetheaugust commented on src/graphicCreatorTask.js
> +    }
це в одну строчку можна було записати

2023-12-15 01:40 UTC, bringmetheaugust commented on src/graphicCreatorTask.js
> +  const valueFalse = "......";
чому ти ці значення виніс в змінні?
аргументуй

2023-12-15 01:40 UTC, bringmetheaugust commented on src/setOneDownTask.js
> +//   console.log(setStrValue("Uif usjdl up uijt lbub"));
це вообще непонятно яка задача. знову в PR попало то, шо не треба

2023-12-15 01:41 UTC, bringmetheaugust commented
і всі файли (модулі) повині закічуватись з пустої строки.
це не обов'язково, але так просить сам **git**

2023-12-15 13:21 UTC, Nitroglicerine commented on src/graphicCreatorTask.js
> +  let diagramArray = [...args];
тут буде переприсвоювання на 5 лінії,але помилку в Імені я виправивю В 6 змінив на const

2023-12-15 13:22 UTC, Nitroglicerine commented on src/setOneDownTask.js
> +    if (typeof str === "string") {
Переробив

2023-12-15 13:22 UTC, Nitroglicerine commented on src/setOneDownTask.js
> +
убрав

2023-12-15 13:22 UTC, Nitroglicerine commented on src/setOneDownTask.js
> +        }
Переписав на тернарник

2023-12-15 14:06 UTC, merged

2023-12-15 16:30 UTC, bringmetheaugust commented on src/setOneDownTask.js
> +        }
не бачу це в PR. ти або не закомітив, або не в цій гілці зробив

2023-12-15 16:34 UTC, bringmetheaugust reviewed
переробити

2023-12-15 16:34 UTC, bringmetheaugust commented on src/graphicCreatorTask.js
> +    iterator !== 10 ? (scalecolumn = " | ") : scalecolumn;
це шо за брєд?

2023-12-15 16:35 UTC, bringmetheaugust commented
і якого хуя цей PR замерджено?
там багато шо переробити треба